### ISSUE TITLE
inspect against docker:// scheme panics

### ISSUE THREAD

**Issue by raharper** [raharper/ocidist#4]
```
$ ./bin/ocidist inspect docker://192.168.23.52:9001/foo/services/svc:v2.1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcd9881]

goroutine 1 [running]:
github.com/bloodorangeio/reggie.(*Client).NewRequest(0x0, {0xf6c4ee, 0x3}, {0xf8dae5, 0x1d}, {0xc0001df500, 0x2, 0xc0003679e0?})
	/home/rharper/go/pkg/mod/github.com/bloodorangeio/reggie@v0.6.1/client.go:154 +0x61
github.com/raharper/ocidist/pkg/api.(*OCIDistRepo).GetManifest(0xc000367c60)
	/home/rharper/work/git/raharper/ocidist/pkg/api/ocidist.go:120 +0x61d
github.com/raharper/ocidist/cmd/ocidist/cmd.doInspect(0x172eaa0?, {0xc0003676d0?, 0x1?, 0x1?})
	/home/rharper/work/git/raharper/ocidist/cmd/ocidist/cmd/inspect.go:92 +0xbf
github.com/spf13/cobra.(*Command).execute(0x172eaa0, {0xc0003676a0, 0x1, 0x1})
	/home/rharper/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x172f060)
	/home/rharper/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/rharper/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/raharper/ocidist/cmd/ocidist/cmd.Execute()
	/home/rharper/work/git/raharper/ocidist/cmd/ocidist/cmd/root.go:46 +0x25
main.main()
	/home/rharper/work/git/raharper/ocidist/cmd/ocidist/main.go:21 +0x17
     ..:(╯°□°)╯彡┻━━┻
```

looks like ocidist is passing the docker string to reggie.

**Comment by raharper** [comment]
This was fixed with PR #6
